// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function TestNetwork(arg1:Array<string>,arg2:string,arg3:number):Promise<Array<any>>;
